plugin_repo(
    name = "docker",
    owner = "please-build",
    plugin = "docker-rules",
    revision = "v0.1.0",
)

plugin_repo(
    name = "shell",
    owner = "please-build",
    plugin = "shell-rules",
    revision = "v0.2.0",
)
